-- AlterTable
ALTER TABLE `grades` MODIFY `giverRole` ENUM('SISWA', 'KETUA', 'GURU_PEMBIMBING', 'ADMIN', 'DUDI', 'KEPALA_SEKOLAH', 'SUPER_ADMIN') NOT NULL;

-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('SISWA', 'KETUA', 'GURU_PEMBIMBING', 'ADMIN', 'DUDI', 'KEPALA_SEKOLAH', 'SUPER_ADMIN') NOT NULL;
