-- DropForeignKey
ALTER TABLE `attendances` DROP FOREIGN KEY `Attendance_verifiedById_fkey`;

-- AlterTable
ALTER TABLE `attendances` MODIFY `activity` TEXT NULL;

-- AlterTable
ALTER TABLE `documents` MODIFY `type` ENUM('SURAT_PERMOHONAN', 'SURAT_PENGANTAR', 'SURAT_PENERIMAAN', 'SURAT_PERNYATAAN', 'SURAT_PENUGASAN', 'LAPORAN_AKHIR', 'SURAT_PENARIKAN', 'LAINNYA') NOT NULL;

-- AlterTable
ALTER TABLE `generated_letters` MODIFY `type` ENUM('SURAT_PERMOHONAN', 'SURAT_PENGANTAR', 'SURAT_PENERIMAAN', 'SURAT_PERNYATAAN', 'SURAT_PENUGASAN', 'LAPORAN_AKHIR', 'SURAT_PENARIKAN', 'LAINNYA') NOT NULL;

-- AddForeignKey
ALTER TABLE `attendances` ADD CONSTRAINT `attendances_verifiedById_fkey` FOREIGN KEY (`verifiedById`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
